CREATE TABLE tt_content (
	tx_containeritems_a_autocollapse int(1) DEFAULT NULL,
	tx_containeritems_a_firstopen int(1) DEFAULT NULL,
	tx_containeritems_classes varchar(25),
	tx_containeritems_customid varchar(25),
	tx_containeritems_s_aligncontent varchar(25),
  tx_containeritems_s_framepadding varchar(25),
	tx_containeritems_s_contentwidth varchar(25),
  tx_containeritems_s_fullheight smallint(1) DEFAULT NULL,
  tx_containeritems_s_valign varchar(7),
	tx_containeritems_s_textcolorselect varchar(25),
	tx_containeritems_s_bgcolorselect varchar(25),
	tx_containeritems_s_bgimagewidth varchar(25),
	tx_containeritems_s_bgmediaeffect varchar(25),
	tx_containeritems_s_bgvideosound tinyint DEFAULT NULL,
  tx_containeritems_s_bgvideoclearframe tinyint DEFAULT NULL,
  tx_containeritems_s_bgvideoonoloop tinyint DEFAULT NULL,
	tx_containeritems_s_bgplacement varchar(25),
	tx_containeritems_s_bgfixed tinyint DEFAULT NULL,
	tx_containeritems_s_bgoverlay varchar(25),
	tx_containeritems_s_bgoverlaydark varchar(25),
	tx_containeritems_s_bgoverlayfilters int(1) DEFAULT NULL,
	tx_containeritems_s_bgoverlayblur smallint DEFAULT NULL,
	tx_containeritems_s_bgoverlaysaturate smallint DEFAULT NULL,
	tx_containeritems_s_bgoverlayhue smallint DEFAULT NULL,
	tx_containeritems_s_bgoverlaybrightness smallint DEFAULT NULL,
	tx_containeritems_s_bgoverlaysepia smallint DEFAULT NULL,
	tx_containeritems_b_style varchar(25),
	tx_containeritems_siema_style varchar(25),
	tx_containeritems_siema_startindex int(1) DEFAULT NULL,
	tx_containeritems_siema_loop int(1) DEFAULT NULL,
	tx_containeritems_siema_pagination varchar(25),
	tx_containeritems_siema_nav int(1) DEFAULT NULL,
);
