CREATE TABLE tt_content (
	tx_containeritems_a_stayopen int(1) DEFAULT NULL,
	tx_containeritems_a_firstopen int(1) DEFAULT NULL,
	tx_containeritems_classes varchar(25),
	tx_containeritems_s_aligncontent varchar(25),
  tx_containeritems_s_framepadding varchar(25),
	tx_containeritems_s_fullwidth smallint(1) DEFAULT NULL,
  tx_containeritems_s_fullheight smallint(1) DEFAULT NULL,
  tx_containeritems_s_valign varchar(7),
	tx_containeritems_s_textcolorselect varchar(25),
	tx_containeritems_s_textcolor varchar(25),
	tx_containeritems_s_bgcolorselect varchar(25),
	tx_containeritems_s_bgcolor varchar(25),
	tx_containeritems_s_bgimagewidth varchar(25),
	tx_containeritems_s_bgimgeffect varchar(25),
	tx_containeritems_s_bgvideosound tinyint DEFAULT NULL,
  tx_containeritems_s_bgvideoclearframe tinyint DEFAULT NULL,
  tx_containeritems_s_bgvideoonoloop tinyint DEFAULT NULL,
	tx_containeritems_s_bgplacement varchar(25),
	tx_containeritems_s_bgfixed tinyint DEFAULT NULL,
	tx_containeritems_s_bgoverlay varchar(25),
	tx_containeritems_s_bgoverlaydark varchar(25),
	tx_containeritems_s_bgoverlayfilters int(1) DEFAULT NULL,
	tx_containeritems_s_bgoverlayblur smallint DEFAULT NULL,
	tx_containeritems_s_bgoverlaysaturate smallint DEFAULT NULL,
	tx_containeritems_s_bgoverlayhue smallint DEFAULT NULL,
	tx_containeritems_s_bgoverlaybrightness smallint DEFAULT NULL,
	tx_containeritems_s_bgoverlaysepia smallint DEFAULT NULL,
	tx_containeritems_b_style varchar(25),
);
